### ISSUE TITLE
SuiteSparse can be compiled without CHOLMOD, `get_ldup` argument type breaks compiling

### ISSUE THREAD

**Issue by peteristhegreat** [ElOceanografo/SparseInverseSubset.jl#3]
https://github.com/JuliaSparse/SuiteSparse.jl/blob/master/src/SuiteSparse.jl#L13

https://github.com/ElOceanografo/SparseInverseSubset.jl/commit/f98115d296d2923bb44cc6f50da8f1a3699abd29

In a commercial setting, I have a copy of julia without GPL libraries.

So `SuiteSparse` compiles without `CHOLMOD`.

```
if Base.USE_GPL_LIBS
    const CHOLMOD = SparseArrays.CHOLMOD
    const SPQR = SparseArrays.SPQR
    const UMFPACK = SparseArrays.UMFPACK
end
```

Then when `SparseInverseSubset` gets downloaded during an `instantiate`, it fails to compile:

```
ERROR: LoadError: UndefVarError: CHOLMOD not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:26
 [2] top-level scope
   @ ~/.julia/packages/SparseInverseSubset/l3ksN/src/SparseInverseSubset.jl:42
 [3] include
   @ ./Base.jl:384 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1235
 [5] top-level scope
   @ none:1
 [6] eval
   @ ./boot.jl:360 [inlined]
 [7] eval(x::Expr)
   @ Base.MainInclude ./client.jl:446
 [8] top-level scope
   @ none:1
in expression starting at /root/.julia/packages/SparseInverseSubset/l3ksN/src/SparseInverseSubset.jl:1
```

Please keep the dependence on `CHOLMOD` optional and not reference it in the arg for `get_ldup`.

Loose typing how it was before the docstring update should fix it for me.

Thanks!

**Comment by ElOceanografo** [comment]
Can you confirm what your dependency chain is that is importing SparseInverseSubset? Is it through ChainRules?

I will revert to the loose typing for now, but there should probably be a conditional import statement in ChainRules to handle non-GPL Julia builds. See also this PR: https://github.com/ElOceanografo/SparseInverseSubset.jl/pull/2

**Comment by peteristhegreat** [comment]
You are correct about it coming in through `ChainRules.jl`.

Searching through my `~/.julia/packages` folder and in my `Manifest.toml` confirmed your suspicions.

```
$ cd ~/.julia/packages
$ grep -r -I SparseInverseSubset *
ChainRules/pEOSw/Project.toml:SparseInverseSubset = "dc90abb0-5640-4711-901d-7e5b23a2fada"
ChainRules/pEOSw/Project.toml:SparseInverseSubset = "0.1"
ChainRules/pEOSw/src/rulesets/LinearAlgebra/structured.jl:using SparseInverseSubset
ChainRules/pEOSw/src/rulesets/SparseArrays/sparsematrix.jl:    L, D, U, P = SparseInverseSubset.get_ldup(F)
SparseInverseSubset/l3ksN/test/runtests.jl:using SparseInverseSubset
SparseInverseSubset/l3ksN/test/runtests.jl:@testset verbose=true "SparseInverseSubset.jl" begin
SparseInverseSubset/l3ksN/README.md:# SparseInverseSubset.jl
SparseInverseSubset/l3ksN/README.md:[![Build Status](https://github.com/ElOceanografo/SparseInverseSubset.jl/actions/workflows/CI.yml/badge.svg?branch=main)](https://github.com/ElOceanografo/SparseInverseSubset.jl/actions/workflows/CI.yml?query=branch%3Amain)
SparseInverseSubset/l3ksN/README.md:using SparseInverseSubset
SparseInverseSubset/l3ksN/Project.toml:name = "SparseInverseSubset"
SparseInverseSubset/l3ksN/src/SparseInverseSubset.jl:module SparseInverseSubset
```

Thanks for the followup.

**Comment by ElOceanografo** [comment]
Have loosened the typing on `get_ldup` as a patch [here](https://github.com/ElOceanografo/SparseInverseSubset.jl/commit/07b8871a2b546bfcc2ae413ecdc1fa38fbd79b24), and opened https://github.com/JuliaDiff/ChainRules.jl/issues/763 at ChainRules as a permanent fix. Closing this for now.
